apiVersion: v1
kind: Service
metadata:
  name: podinfo-test-connect
  labels:
    # Enables "zarf connect feature"
    zarf.dev/connect-name: podinfo
  annotations:
    zarf.dev/connect-description: "The podinfo page"
spec:
  selector:
    #app.kubernetes.io/instance: podinfo
    app.kubernetes.io/name: podinfo
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9898
---